# PROJET 2 - PREPARATION DU FICHIER POUR LE MACHINE LEARNING

In [62]:
import pandas as pd
import numpy as np

## Charger le dataframe CSV

In [63]:
merge_final_nettoye_2 = pd.read_csv("../DATASETS NETTOYES/merge_final_2.csv", sep = ",")

In [64]:
# On ajoute l'année après le nom du film pour éviter la confusion si plusieurs films avec le même titre
merge_final_nettoye_2['primaryTitle'] = merge_final_nettoye_2['primaryTitle']+ ' (' + merge_final_nettoye_2['startYear'].map(str) + ')'
merge_final_nettoye_2['originalTitle'] = merge_final_nettoye_2['originalTitle']+ ' (' + merge_final_nettoye_2['startYear'].map(str) + ')'
merge_final_nettoye_2['French_Title'] = merge_final_nettoye_2['French_Title']+ ' (' + merge_final_nettoye_2['startYear'].map(str) + ')'

In [65]:
merge_final_nettoye_2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.3,407.0,"Suzanne Le Bret,Léonce Perret,Louis Leubas,Mau..."
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5141.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16045.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turn..."
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1070.0,"René Cresté,Musidora,René Poyen,Édouard Mathé,..."
4,tt0008879,The Outlaw and His Wife (1918),Berg-Ejvind och hans hustru (1918),1918,136.0,Drama,Les Proscrits (1918),7.2,1983.0,"Victor Sjöström,Edith Erastoff,John Ekman,Nils..."
...,...,...,...,...,...,...,...,...,...,...
12431,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Adventure,Crime",Kaithi (2019),8.5,35428.0,"Karthi,Narain,Arjun Das,George Maryan,Lokesh K..."
12432,tt9904844,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,493.0,Tarvo Mölder
12433,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,678.0,"Lal,Akshara Kishor,Iniya,Narain,T.V. Chandran"
12434,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.5,2885.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
12435,tt9911774,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.1,379.0,"Anoop Chandran,Indrans,Sona Nair"

## Enregistrer le fichier corrigé sur l'ordi en PICKLE

In [66]:
merge_final_nettoye_2.to_pickle("../DATASETS NETTOYES/merge_final_nettoye_2.pkl.gz", compression = 'gzip')

## Charger le dataframe PICKLE

In [67]:
merge_final_nettoye_Pkl_2 = pd.read_pickle("../DATASETS NETTOYES/merge_final_nettoye_2.pkl.gz")

In [68]:
merge_final_nettoye_Pkl_2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.3,407.0,"Suzanne Le Bret,Léonce Perret,Louis Leubas,Mau..."
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5141.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16045.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turn..."
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1070.0,"René Cresté,Musidora,René Poyen,Édouard Mathé,..."
4,tt0008879,The Outlaw and His Wife (1918),Berg-Ejvind och hans hustru (1918),1918,136.0,Drama,Les Proscrits (1918),7.2,1983.0,"Victor Sjöström,Edith Erastoff,John Ekman,Nils..."
...,...,...,...,...,...,...,...,...,...,...
12431,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Adventure,Crime",Kaithi (2019),8.5,35428.0,"Karthi,Narain,Arjun Das,George Maryan,Lokesh K..."
12432,tt9904844,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,493.0,Tarvo Mölder
12433,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,678.0,"Lal,Akshara Kishor,Iniya,Narain,T.V. Chandran"
12434,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.5,2885.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
12435,tt9911774,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.1,379.0,"Anoop Chandran,Indrans,Sona Nair"

# METHODE DUMMIES

## Spliter les genres

In [69]:
# encodage + tranformation en boolean
df_genres_2 = merge_final_nettoye_Pkl_2["genres"].str.get_dummies(sep=',').astype(bool) 
df_genres_2

,Action,Adventure,Animation,Biography,Comedy,Crime,Divers,Documentary,Drama,Family,...,Mystery,News,Reality-TV,Romance,Sci-Fi,Sport,Talk-Show,Thriller,War,Western
0,False,False,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,True,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12431,True,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12432,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,False
12433,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
12434,False,False,False,False,True,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
12435,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False

In [70]:
# on concat sur les colonnes le df_genres avec le df d'origne sans la colonne "genres"
df_dummies_2 = pd.concat([merge_final_nettoye_Pkl_2.drop(columns="genres"), df_genres_2 ], axis=1)
df_dummies_2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,French_Title,averageRating,numVotes,primaryName,Action,...,Mystery,News,Reality-TV,Romance,Sci-Fi,Sport,Talk-Show,Thriller,War,Western
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,L'Enfant de Paris (1913),7.3,407.0,"Suzanne Le Bret,Léonce Perret,Louis Leubas,Mau...",False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,Les vampires (1915),7.3,5141.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar...",True,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,Intolérance (1916),7.7,16045.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turn...",False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,Judex (1916),7.2,1070.0,"René Cresté,Musidora,René Poyen,Édouard Mathé,...",False,...,False,False,False,False,False,False,False,False,False,False
4,tt0008879,The Outlaw and His Wife (1918),Berg-Ejvind och hans hustru (1918),1918,136.0,Les Proscrits (1918),7.2,1983.0,"Victor Sjöström,Edith Erastoff,John Ekman,Nils...",False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12431,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,Kaithi (2019),8.5,35428.0,"Karthi,Narain,Arjun Das,George Maryan,Lokesh K...",True,...,False,False,False,False,False,False,False,False,False,False
12432,tt9904844,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,NaN,8.1,493.0,Tarvo Mölder,False,...,False,False,False,False,False,True,False,False,False,False
12433,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,NaN,7.6,678.0,"Lal,Akshara Kishor,Iniya,Narain,T.V. Chandran",False,...,False,False,False,False,False,False,False,False,False,False
12434,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,De Beentjes van Sint-Hildegard (2020),7.5,2885.0,"Herman Finkers,Johanna ter Steege,Leonie ter B...",False,...,False,False,False,False,False,False,False,False,False,False
12435,tt9911774,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,NaN,8.1,379.0,"Anoop Chandran,Indrans,Sona Nair",False,...,False,False,False,False,False,False,False,False,False,False

## Spliter les Startyear (ne se fait plus)

In [10]:
# encodage + tranformation en boolean  en convertissant en string car get dummies est une methode en string
df_startyear_2 = df_dummies_2["startYear"].astype(str).str.get_dummies(sep=',').astype(bool) 
df_startyear_2

,1913,1915,1916,1918,1919,1920,1921,1922,1923,1924,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12428,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
12429,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
12430,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
12431,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
12432,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [11]:
# on concat sur les colonnes le df_primaryName avec le df_dummies sans la colonne "primaryName"
df_dummies_2 = pd.concat([df_dummies_2.drop(columns="startYear"), df_startyear_2 ], axis=1)
df_dummies_2

,tconst,primaryTitle,originalTitle,runtimeMinutes,French_Title,averageRating,numVotes,primaryName,Action,Adventure,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),124.0,L'Enfant de Paris (1913),7.3,407.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém...",False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,Les vampires (1915),Les vampires (1915),421.0,Les vampires (1915),7.3,5141.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar...",True,True,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,163.0,Intolérance (1916),7.7,16045.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner",False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,Judex (1916),Judex (1916),300.0,Judex (1916),7.2,1070.0,"René Cresté,Musidora,René Poyen,Édouard Mathé",False,True,...,False,False,False,False,False,False,False,False,False,False
4,tt0008879,The Outlaw and His Wife (1918),Berg-Ejvind och hans hustru (1918),136.0,Les Proscrits (1918),7.2,1983.0,"Victor Sjöström,Edith Erastoff,John Ekman,Nils...",False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12428,tt9900782,Kaithi (2019),Kaithi (2019),145.0,Kaithi (2019),8.5,35428.0,"Karthi,Narain,Arjun Das,George Maryan",True,True,...,False,False,False,False,False,True,False,False,False,False
12429,tt9904844,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),125.0,NaN,8.1,493.0,NaN,False,False,...,False,False,False,False,False,True,False,False,False,False
12430,tt9905462,Pengalila (2019),Pengalila (2019),111.0,NaN,7.6,678.0,NaN,False,False,...,False,False,False,False,False,True,False,False,False,False
12431,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),103.0,De Beentjes van Sint-Hildegard (2020),7.5,2885.0,"Herman Finkers,Johanna ter Steege,Leonie ter B...",False,False,...,False,False,False,False,False,False,True,False,False,False
12432,tt9911774,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),130.0,NaN,8.1,379.0,NaN,False,False,...,False,False,False,False,False,True,False,False,False,False

## Spliter les runtimeMinutes (ne se fait plus)

In [12]:
df_runtimeminutes_2 = df_dummies_2["runtimeMinutes"].astype(str).str.get_dummies(sep=',').astype(bool) 
df_runtimeminutes_2

,100.0,101.0,102.0,103.0,104.0,105.0,106.0,107.0,108.0,109.0,...,90.0,91.0,92.0,93.0,94.0,95.0,96.0,97.0,98.0,99.0
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12428,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12429,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12430,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12431,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12432,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
# on concat sur les colonnes le df_primaryName avec le df_dummies sans la colonne "primaryName"
df_dummies_2 = pd.concat([df_dummies_2.drop(columns="runtimeMinutes"), df_runtimeminutes_2 ], axis=1)
df_dummies_2

,tconst,primaryTitle,originalTitle,French_Title,averageRating,numVotes,primaryName,Action,Adventure,Animation,...,90.0,91.0,92.0,93.0,94.0,95.0,96.0,97.0,98.0,99.0
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),L'Enfant de Paris (1913),7.3,407.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém...",False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,Les vampires (1915),Les vampires (1915),Les vampires (1915),7.3,5141.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar...",True,True,False,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,Intolérance (1916),7.7,16045.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner",False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,Judex (1916),Judex (1916),Judex (1916),7.2,1070.0,"René Cresté,Musidora,René Poyen,Édouard Mathé",False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,tt0008879,The Outlaw and His Wife (1918),Berg-Ejvind och hans hustru (1918),Les Proscrits (1918),7.2,1983.0,"Victor Sjöström,Edith Erastoff,John Ekman,Nils...",False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12428,tt9900782,Kaithi (2019),Kaithi (2019),Kaithi (2019),8.5,35428.0,"Karthi,Narain,Arjun Das,George Maryan",True,True,False,...,False,False,False,False,False,False,False,False,False,False
12429,tt9904844,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),NaN,8.1,493.0,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12430,tt9905462,Pengalila (2019),Pengalila (2019),NaN,7.6,678.0,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12431,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),De Beentjes van Sint-Hildegard (2020),7.5,2885.0,"Herman Finkers,Johanna ter Steege,Leonie ter B...",False,False,False,...,False,False,False,False,False,False,False,False,False,False
12432,tt9911774,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),NaN,8.1,379.0,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Spliter les primaryName

In [71]:
# encodage + tranformation en boolean
df_primaryName_2 = df_dummies_2["primaryName"].str.get_dummies(sep=',').astype(bool) 
df_primaryName_2

,'Ganja' Karuppu,'University' Jeevan,A Martinez,A. Jagannathan,A. Karunakaran,A. Kodandarami Reddy,A. Michael Baldwin,A. Pradeep,A. Sarkunam,A. Venkatesh,...,Ülkü Özen,Ümit Cin Güven,Ümit Ünal,Ümmü Putgül,Ünal Gürel,Üstün Asutay,Þorsteinn Bachmann,Þröstur Leó Gunnarsson,Þórhallur Sigurðsson,Þórhildur Þorleifsdóttir
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12431,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12432,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12433,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12434,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12435,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [72]:
# on concat sur les colonnes le df_primaryName avec le df_dummies sans la colonne "primaryName"
df_dummies_2 = pd.concat([df_dummies_2.drop(columns="primaryName"), df_primaryName_2 ], axis=1)
df_dummies_2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,French_Title,averageRating,numVotes,Action,Adventure,...,Ülkü Özen,Ümit Cin Güven,Ümit Ünal,Ümmü Putgül,Ünal Gürel,Üstün Asutay,Þorsteinn Bachmann,Þröstur Leó Gunnarsson,Þórhallur Sigurðsson,Þórhildur Þorleifsdóttir
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,L'Enfant de Paris (1913),7.3,407.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,Les vampires (1915),7.3,5141.0,True,True,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,Intolérance (1916),7.7,16045.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,Judex (1916),7.2,1070.0,False,True,...,False,False,False,False,False,False,False,False,False,False
4,tt0008879,The Outlaw and His Wife (1918),Berg-Ejvind och hans hustru (1918),1918,136.0,Les Proscrits (1918),7.2,1983.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12431,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,Kaithi (2019),8.5,35428.0,True,True,...,False,False,False,False,False,False,False,False,False,False
12432,tt9904844,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,NaN,8.1,493.0,False,False,...,False,False,False,False,False,False,False,False,False,False
12433,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,NaN,7.6,678.0,False,False,...,False,False,False,False,False,False,False,False,False,False
12434,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,De Beentjes van Sint-Hildegard (2020),7.5,2885.0,False,False,...,False,False,False,False,False,False,False,False,False,False
12435,tt9911774,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,NaN,8.1,379.0,False,False,...,False,False,False,False,False,False,False,False,False,False

## Enregistrer le nouveau fichier dummies en PICKLE

In [73]:
df_dummies_2.to_pickle("../df_machine_learning.pkl.gz", compression = "gzip")

## Charger le fichier dummies en PICKLE

In [74]:
df_machine_learning = pd.read_pickle("../df_machine_learning.pkl.gz")

In [75]:
df_machine_learning

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,French_Title,averageRating,numVotes,Action,Adventure,...,Ülkü Özen,Ümit Cin Güven,Ümit Ünal,Ümmü Putgül,Ünal Gürel,Üstün Asutay,Þorsteinn Bachmann,Þröstur Leó Gunnarsson,Þórhallur Sigurðsson,Þórhildur Þorleifsdóttir
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,L'Enfant de Paris (1913),7.3,407.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,Les vampires (1915),7.3,5141.0,True,True,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,Intolérance (1916),7.7,16045.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,Judex (1916),7.2,1070.0,False,True,...,False,False,False,False,False,False,False,False,False,False
4,tt0008879,The Outlaw and His Wife (1918),Berg-Ejvind och hans hustru (1918),1918,136.0,Les Proscrits (1918),7.2,1983.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12431,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,Kaithi (2019),8.5,35428.0,True,True,...,False,False,False,False,False,False,False,False,False,False
12432,tt9904844,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,NaN,8.1,493.0,False,False,...,False,False,False,False,False,False,False,False,False,False
12433,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,NaN,7.6,678.0,False,False,...,False,False,False,False,False,False,False,False,False,False
12434,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,De Beentjes van Sint-Hildegard (2020),7.5,2885.0,False,False,...,False,False,False,False,False,False,False,False,False,False
12435,tt9911774,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,NaN,8.1,379.0,False,False,...,False,False,False,False,False,False,False,False,False,False